### ISSUE TITLE
Port to Flow

### ISSUE THREAD

**Issue by taooceros** [JohnTheGr8/Wox.Plugin.Github#2]
Would you please port this plugin to Flow Launcher? It seems really useful for me!

**Comment by JohnTheGr8** [comment]
@taooceros will do, thank you for the interest!

**Comment by taooceros** [comment]
> @taooceros will do, thank you for the interest!

Thank you!

**Comment by JohnTheGr8** [comment]
Port is ready at [JohnTheGr8/Flow.Plugin.Github](https://github.com/JohnTheGr8/Flow.Plugin.Github) and can be installed with `pm install Flow.Plugin.Github`
